jobs:
  ReuseableMatrixJobForDeployment:
    strategy:
      matrix:
        target: [dev, stage, prod]
    uses: cloudyfarmers/p-shared-devsecops/.github/workflows/canary-workflow.yml@main
    with:
      target: ${{ matrix.target }}
